package cards;

/**
 * Created by Stephanie on 14/09/2016.
 */
public enum Cleavage {
    NONE, POOR_NONE, POOR1, POOR2, GOOD1, GOOD1_POOR1, GOOD2, GOOD3,
    PERFECT1, PERFECT1_GOOD1, PERFECT1_GOOD2, PERFECT2_GOOD1, PERFECT3,
    PERFECT4, PERFECT6
}
